#!/bin/bash


#text colors

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
black="\e[30m"
gray="\e[37m"

bt=$(tput bold 2)
#reset color

reset=$(tput sgr0)

#decoration

unli="\e[4m"
blink="\e[25m"
#background colors

rbg="\e[101m"
wbg="\e[107m"
cbg="\e[106m"
pbg="\e[105m"
gbg="\e[102m"
bbg="\e[104m"

clear

#banner for shadow


#banner for shadow


echo "${red}░██████╗██╗░░██╗░█████╗░██████╗░░█████╗░░██╗░░░░░░░██╗"
echo "${red}██╔════╝██║░░██║██╔══██╗██╔══██╗██╔══██╗░██║░░██╗░░██║"
echo "${red}╚█████╗░███████║███████║██║░░██║██║░░██║░╚██╗████╗██╔╝"
echo "${red}░╚═══██╗██╔══██║██╔══██║██║░░██║██║░░██║░░████╔═████║░"
echo "${red}██████╔╝██║░░██║██║░░██║██████╔╝╚█████╔╝░░╚██╔╝░╚██╔╝░"
echo "${red}╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░░"
echo -e "     $bt $white$bbg Developed By Ihtisham Ali - Shadow Walker $reset"



echo "${bt}"
echo "${cyan}$bt • YouTube: ${yellow}https://youtube.com/ShadowWalkerYT"

echo "${cyan}$bt • GitHub: ${yellow}https://github.com/ShadowWalker005"

echo "${cyan}$bt • Facebook: ${yellow}https://facebook.com/ShadowWalkerYT"

echo "${cyan}$bt • Blogspot: ${yellow}https://shadowhub.blogspot.com"

echo
echo
echo "${blue}=========================================="
echo
read -p "${bt}${green} ~ Wordlist Name: ${white}" name
touch "$name.txt"
read -r -p "${bt}${green} ~ Enter Words Sperated By Space: ${white}" -a arr
for wl in "${arr[@]}"; do 
   echo "$wl" >> $name.txt
done
echo
echo "${blue}=========================================="
echo
list="$name"
if [[ -f $name.txt ]]; then
    echo "${cyan}${bt} • $name.txt Wordlist Created Successfully!"
    echo 
    path=$(readlink -f $name.txt)
    echo " ${cyan}${bt}Copy This: ${yellow}$path"
    echo "${reset}"
else
    
    echo "${red}${bt} • Sorry, Failed To Create Wordlist"
fi
echo
